import "./globals.css";
import Header from "./components/Header";

export const metadata = {
  title: "Dreaca",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}
